use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::{env, net::IpAddr};

// Generated by scripts/sync-countries.mjs: Shifter provider weight strictly > 250.
pub const COUNTRIES: &[(&str, &str)] = &[
    ("dz", "Algeria"),
    ("ar", "Argentina"),
    ("bd", "Bangladesh"),
    ("by", "Belarus"),
    ("br", "Brazil"),
    ("bg", "Bulgaria"),
    ("ca", "Canada"),
    ("cl", "Chile"),
    ("cn", "China"),
    ("co", "Colombia"),
    ("hr", "Croatia"),
    ("cz", "Czech Republic"),
    ("eg", "Egypt"),
    ("fr", "France"),
    ("de", "Germany"),
    ("gh", "Ghana"),
    ("gr", "Greece"),
    ("hu", "Hungary"),
    ("in", "India"),
    ("id", "Indonesia"),
    ("ir", "Iran"),
    ("il", "Israel"),
    ("it", "Italy"),
    ("jp", "Japan"),
    ("kz", "Kazakhstan"),
    ("my", "Malaysia"),
    ("mx", "Mexico"),
    ("ma", "Morocco"),
    ("np", "Nepal"),
    ("nl", "Netherlands"),
    ("ng", "Nigeria"),
    ("pe", "Peru"),
    ("ph", "Philippines"),
    ("pl", "Poland"),
    ("pt", "Portugal"),
    ("ro", "Romania"),
    ("ru", "Russia"),
    ("sa", "Saudi Arabia"),
    ("rs", "Serbia"),
    ("sg", "Singapore"),
    ("si", "Slovenia"),
    ("za", "South Africa"),
    ("kr", "South Korea"),
    ("es", "Spain"),
    ("lk", "Sri Lanka"),
    ("tw", "Taiwan"),
    ("th", "Thailand"),
    ("tr", "Turkey"),
    ("ua", "Ukraine"),
    ("ae", "United Arab Emirates"),
    ("gb", "United Kingdom"),
    ("us", "United States"),
    ("ve", "Venezuela"),
    ("vn", "Vietnam"),
];
pub fn valid_country(country: &str) -> bool {
    COUNTRIES.iter().any(|(code, _)| *code == country)
}
pub fn random_id() -> String {
    hex::encode(rand::random::<[u8; 16]>())
}
pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as u64
}
pub fn is_id(s: &str) -> bool {
    s.len() == 32 && s.bytes().all(|c| c.is_ascii_hexdigit())
}

#[derive(Clone)]
pub struct Config {
    pub role: String,
    pub replica: String,
    pub listen: String,
    pub redis: String,
    pub redis_ca_file: Option<String>,
    pub control_origin: String,
    pub integrations: Vec<Integration>,
    pub captcha_site_key: String,
    pub captcha_secret: String,
    pub runtime_origin: String,
    pub region: String,
    pub upstream_host: String,
    pub upstream_port: u16,
    pub upstream_ips: Vec<IpAddr>,
    pub account: String,
    pub password: String,
    pub duration_ms: u64,
    pub byte_limit: u64,
    pub max_streams: usize,
    pub stream_rate: u64,
    pub stream_burst: u64,
    pub connect_timeout: u64,
    pub idle_timeout: u64,
    pub test_mode: bool,
    pub web_dir: String,
}
#[derive(Clone, Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct Integration {
    pub origin: String,
    pub site: String,
}

pub fn integrations(value: &str, runtime: &str, production: bool) -> Result<Vec<Integration>> {
    let entries: Vec<Integration> =
        serde_json::from_str(value).map_err(|_| anyhow::anyhow!("invalid INTEGRATIONS JSON"))?;
    if entries.is_empty() {
        bail!("INTEGRATIONS must not be empty");
    }
    let mut origins = std::collections::HashSet::new();
    for entry in &entries {
        validate_origins(&entry.origin, runtime, production)?;
        // Explicit origin aliases may share a site's identity/quota namespace.
        // Origins themselves must stay unique so routing remains unambiguous.
        if !origins.insert(&entry.origin)
            || entry.site.is_empty()
            || entry.site.len() > 64
            || !entry
                .site
                .bytes()
                .all(|c| c.is_ascii_alphanumeric() || c == b'-')
        {
            bail!("INTEGRATIONS requires unique origins and valid alphanumeric site IDs");
        }
    }
    Ok(entries)
}

pub fn validate_captcha(site_key: &str, secret: &str, production: bool) -> Result<()> {
    const TEST_SITE: &str = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI";
    const TEST_SECRET: &str = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe";
    if production
        && (site_key.is_empty()
            || secret.is_empty()
            || site_key == TEST_SITE
            || secret == TEST_SECRET)
    {
        bail!("production API requires real reCAPTCHA v2 credentials");
    }
    Ok(())
}

#[derive(Deserialize)]
struct Secrets {
    shifter: Account,
}
#[derive(Deserialize)]
struct Account {
    account: String,
    password: String,
}

fn val(key: &str, default: &str) -> String {
    env::var(key).unwrap_or_else(|_| default.into())
}
fn number(key: &str, default: u64) -> Result<u64> {
    let n = val(key, &default.to_string())
        .parse::<u64>()
        .with_context(|| format!("invalid {key}"))?;
    if n == 0 {
        bail!("{key} must be positive");
    }
    Ok(n)
}
impl Config {
    pub async fn load() -> Result<Self> {
        let environment = val("APP_ENV", "development");
        if !["development", "test", "production"].contains(&environment.as_str()) {
            bail!("APP_ENV must be development, test, or production");
        }
        let production = environment == "production";
        let control_origin = val("CONTROL_ORIGIN", "http://localhost:8080");
        let runtime_origin = val("RUNTIME_ORIGIN", "http://localhost:8081");
        let configured_integrations = if production {
            env::var("INTEGRATIONS").context("production requires explicit INTEGRATIONS")?
        } else {
            val(
                "INTEGRATIONS",
                &serde_json::json!([{"origin":control_origin,"site":"local"}]).to_string(),
            )
        };
        let integrations = integrations(&configured_integrations, &runtime_origin, production)?;
        let redis = match env::var("REDIS_URL_FILE") {
            Ok(path) => std::fs::read_to_string(path)
                .map_err(|_| anyhow::anyhow!("cannot read REDIS_URL_FILE"))?
                .trim()
                .to_owned(),
            Err(_) => val("REDIS_URL", "redis://redis:6379/"),
        };
        if production {
            let (host, port) = production_redis(&redis)?;
            let addresses: Vec<_> = tokio::net::lookup_host((host.as_str(), port))
                .await
                .map_err(|_| anyhow::anyhow!("production Redis private DNS lookup failed"))?
                .collect();
            if addresses.is_empty() || addresses.iter().any(|a| !private_ip(a.ip())) {
                bail!("production Redis must resolve only to private RFC1918/ULA addresses");
            }
        }
        let test_mode = environment == "test";
        let role = val("ROLE", "api");
        if !["api", "gateway"].contains(&role.as_str()) {
            bail!("invalid ROLE");
        }
        let captcha_site_key = val("RECAPTCHA_SITE_KEY", "");
        // Only the API process receives the verification secret.
        let captcha_secret = if role == "api" {
            match env::var("RECAPTCHA_SECRET_FILE") {
                Ok(path) if !path.is_empty() => std::fs::read_to_string(path)
                    .map_err(|_| anyhow::anyhow!("cannot read RECAPTCHA_SECRET_FILE"))?
                    .trim()
                    .to_owned(),
                _ => String::new(),
            }
        } else {
            String::new()
        };
        if role == "api" {
            validate_captcha(&captcha_site_key, &captcha_secret, production)?;
        }
        let region = val("SHIFTER_REGION", "blr");
        if !["fra", "ams", "lon", "nyc", "tor", "sgp", "blr", "syd"].contains(&region.as_str()) {
            bail!("invalid region");
        }
        let upstream_host = if test_mode {
            "mock-upstream".into()
        } else {
            format!("{region}.p.shifter.io")
        };
        let upstream_port = if test_mode { 1080 } else { 443 };
        let (account, password) = if test_mode {
            ("fixture".into(), "fixture-password".into())
        } else if role == "gateway" {
            let path = val("CREDENTIALS_FILE", "/run/secrets/shifter_credentials");
            let contents =
                std::fs::read_to_string(path).context("cannot read credential secret")?;
            // Do not expose TOML parse errors: they may include the secret's source line.
            let secrets: Secrets = toml::from_str(&contents)
                .map_err(|_| anyhow::anyhow!("invalid credential secret"))?;
            (
                secrets
                    .shifter
                    .account
                    .trim_start_matches("customer-")
                    .to_string(),
                secrets.shifter.password,
            )
        } else {
            (String::new(), String::new())
        };
        if role == "gateway" {
            if account.is_empty()
                || !account
                    .bytes()
                    .all(|x| x.is_ascii_alphanumeric() || b"._".contains(&x))
            {
                bail!("invalid account syntax");
            }
            if password.is_empty() || !password.is_ascii() || password.len() > 255 {
                bail!("invalid SOCKS password length/encoding");
            }
        }
        let upstream_ips = if role == "gateway" {
            tokio::net::lookup_host((upstream_host.as_str(), upstream_port))
                .await
                .context("upstream DNS unavailable")?
                .map(|x| x.ip())
                .collect()
        } else {
            vec![]
        };
        let cfg = Self {
            role,
            replica: val("REPLICA", "api"),
            listen: val("LISTEN", "0.0.0.0:3000"),
            redis,
            redis_ca_file: env::var("REDIS_CA_FILE").ok().filter(|v| !v.is_empty()),
            control_origin,
            integrations,
            captcha_site_key,
            captcha_secret,
            runtime_origin,
            region,
            upstream_host,
            upstream_port,
            upstream_ips,
            account,
            password,
            duration_ms: number("SESSION_SECONDS", 1800)? * 1000,
            byte_limit: number("BYTE_LIMIT", 100 * 1024 * 1024)?,
            max_streams: number("MAX_STREAMS", 32)? as usize,
            stream_rate: number("STREAM_RATE", 8)?,
            stream_burst: number("STREAM_BURST", 16)?,
            connect_timeout: number("CONNECT_TIMEOUT_SECONDS", 15)?,
            idle_timeout: number("IDLE_TIMEOUT_SECONDS", 60)?,
            test_mode,
            web_dir: val("WEB_DIR", "web"),
        };
        if cfg.duration_ms > 1_800_000 {
            bail!("SESSION_SECONDS must be at most 1800 for the configured sticky TTL");
        }
        if cfg.max_streams > 128 {
            bail!("MAX_STREAMS too large");
        }
        if cfg.role == "gateway" {
            cfg.username("us", &random_id())?;
        }
        Ok(cfg)
    }
    pub fn username(&self, country: &str, sid: &str) -> Result<String> {
        if !valid_country(country) || !is_id(sid) {
            bail!("invalid session routing");
        }
        let user = format!(
            "customer-{}-country-{country}-strict-true-sid-{sid}-ttl-1800-pool-shifter",
            self.account
        );
        if user.len() > 255 {
            bail!("SOCKS username too long");
        }
        Ok(user)
    }
}

fn validate_origins(control: &str, runtime: &str, production: bool) -> Result<()> {
    for origin in [control, runtime] {
        let parsed = url::Url::parse(origin).context("invalid application origin")?;
        if !["http", "https"].contains(&parsed.scheme())
            || parsed.origin().ascii_serialization() != origin
            || parsed.host_str().is_none_or(|host| host.contains('*'))
        {
            bail!(
                "application origins must contain only scheme and host (plus optional port), without trailing slash"
            );
        }
        if production && parsed.scheme() != "https" {
            bail!("production requires HTTPS CONTROL_ORIGIN and RUNTIME_ORIGIN");
        }
    }
    if control == runtime {
        bail!("control and runtime must use separate origins");
    }
    Ok(())
}

fn production_redis(value: &str) -> Result<(String, u16)> {
    use redis::{ConnectionAddr, IntoConnectionInfo};
    // Never include a connection URL or parser error containing credentials.
    let info = value
        .into_connection_info()
        .map_err(|_| anyhow::anyhow!("invalid Redis connection configuration"))?;
    // Current production phase explicitly permits ACL/password auth over private TCP.
    // TLS remains optional, but certificate verification can never be disabled.
    let (host, port) = match info.addr {
        ConnectionAddr::Tcp(host, port) => (host, port),
        ConnectionAddr::TcpTls {
            host,
            port,
            insecure: false,
            ..
        } => (host, port),
        _ => bail!("production Redis requires private TCP or certificate-verified TLS"),
    };
    if !(value.starts_with("redis://") || value.starts_with("rediss://"))
        || info
            .redis
            .username
            .as_deref()
            .is_none_or(|u| u.is_empty() || u == "default")
        || info.redis.password.as_deref().is_none_or(str::is_empty)
    {
        bail!("production Redis requires a named ACL user and password");
    }
    Ok((host, port))
}

fn private_ip(ip: IpAddr) -> bool {
    match ip {
        IpAddr::V4(ip) => ip.is_private(),
        IpAddr::V6(ip) => (ip.segments()[0] & 0xfe00) == 0xfc00,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn explicit_origin_aliases_can_share_a_site() {
        let value = r#"[{"origin":"https://example.com","site":"shifter"},{"origin":"https://second.example.com","site":"ip-info"},{"origin":"https://staging.example.com","site":"shifter"}]"#;
        let entries = integrations(value, "https://proxy.example.net", true).unwrap();
        assert_eq!(entries.len(), 3);
        assert_eq!(entries[0].site, entries[2].site);
        assert_ne!(entries[0].site, entries[1].site);
        for duplicate in [
            r#"[{"origin":"https://example.com","site":"shifter"},{"origin":"https://example.com","site":"shifter"}]"#,
            r#"[{"origin":"https://example.com","site":"shifter"},{"origin":"https://example.com","site":"other"}]"#,
        ] {
            assert!(integrations(duplicate, "https://proxy.example.net", true).is_err());
        }
    }

    #[test]
    fn integrations_and_captcha_are_strict() {
        let value = r#"[{"origin":"https://example.com","site":"shifter"},{"origin":"https://second.example.com","site":"ip-info"}]"#;
        assert_eq!(
            integrations(value, "https://proxy.example.net", true)
                .unwrap()
                .len(),
            2
        );
        for value in [
            "[]",
            r#"[{"origin":"https://*.example.com","site":"x"}]"#,
            r#"[{"origin":"http://example.com","site":"x"}]"#,
            r#"[{"origin":"https://example.com/","site":"x"}]"#,
            r#"[{"origin":"https://example.com","site":"x:y"}]"#,
        ] {
            assert!(integrations(value, "https://proxy.example.net", true).is_err());
        }
        assert!(validate_captcha("", "", true).is_err());
        assert!(
            validate_captcha("6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI", "fixture", true).is_err()
        );
        assert!(
            validate_captcha("fixture", "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe", true).is_err()
        );
    }

    #[test]
    fn production_requires_distinct_https_origins() {
        assert!(
            validate_origins("https://control.example", "https://runtime.example", true).is_ok()
        );
        for runtime in [
            "http://runtime.example",
            "https://control.example",
            "https://runtime.example/",
            "https://runtime.example/path",
            "https://user@runtime.example",
        ] {
            assert!(validate_origins("https://control.example", runtime, true).is_err());
        }
        assert!(validate_origins("http://localhost:8080", "http://localhost:8081", false).is_ok());
    }

    #[test]
    fn production_requires_named_acl_and_verifies_optional_tls() {
        assert!(production_redis("redis://app:fixture@redis:6379/0").is_ok());
        assert!(production_redis("rediss://app:fixture@redis:6379/0").is_ok());
        for value in [
            "redis://redis/",
            "rediss://redis/",
            "rediss://default:fixture@redis/",
            "rediss://app@redis/",
            "rediss://app:fixture@redis/#insecure",
            "invalid-fixture-secret",
        ] {
            let error = production_redis(value).unwrap_err().to_string();
            assert!(!error.contains("fixture"));
        }
    }

    #[test]
    fn redis_addresses_must_be_private() {
        for ip in ["10.0.0.1", "172.16.1.2", "192.168.0.2", "fd00::1"] {
            assert!(private_ip(ip.parse().unwrap()));
        }
        for ip in [
            "8.8.8.8",
            "127.0.0.1",
            "169.254.1.1",
            "::1",
            "::ffff:8.8.8.8",
            "2606:4700:4700::1111",
        ] {
            assert!(!private_ip(ip.parse().unwrap()));
        }
    }
}
